### PR TITLE
Yijun dev2022

### PR DESCRIPTION
**Pull request by ymy5178**

### CODE REVIEW

**Review by Xinyue-Tang — CHANGES_REQUESTED** [review]
In the Game Page(for scenario A), the third question is not working. The Question and answer both show NA, and if I click on one of the answer and then submit it, the app will shut down. For scenario B, the choices also showed NA. Sometimes when you restart a lot of time, the NA will appear. It is same for scenario C. In addition, the format in reference page is not consistent. Overall, I think your app is interesting!

**Comment by ymy5178** [comment]
> In the Game Page(for scenario A), the third question is not working. The Question and answer both show NA, and if I click on one of the answer and then submit it, the app will shut down. For scenario B, the choices also showed NA. Sometimes when you restart a lot of time, the NA will appear. It is same for scenario C. In addition, the format in reference page is not consistent. Overall, I think your app is interesting!

**Comment by ymy5178** [comment]
@Xinyue-Tang Thank you so much!
 I have corrected references, but questions in game page work well in my computer. I will wait for Nurul’s review to see whether there is something wrong in my codes. Thank you!

**Comment by NurulSyafiqah-pixel** [comment]
In the game portion, when i click restart to try again more than 2 times , the multiple choices become NA for all other scenarios.

**Review by NurulSyafiqah-pixel — COMMENTED** [review]
Hi, I see the NA problem has resolved now. Good job.

**Pull request closed without merging**
